
current_course: "70_Smile.pdf"

system_prompts:
  template: "prompt/src/template/rascef_C_temp.txt"
  components:
    summary: "prompt/src/no_summary_C.txt"

initial_user_prompts:
  template: "prompt/src/init_content_C.txt"
  components:
    lesson_plans: "prompt/src/lesson_plans/70_Smile_C.txt"